Stemming

In [1]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2026.2.19)
Requirement already satisfied: tqdm in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
word = ['change','changing','changes','changed']

In [3]:
word

['change', 'changing', 'changes', 'changed']

Stemmization

In [5]:
from nltk.stem import PorterStemmer

In [6]:
p=PorterStemmer()

In [7]:
for w in word:
    print(p.stem(w))

chang
chang
chang
chang

In [8]:
for w in word:
    print(w,p.stem(w))

change chang
changing chang
changes chang
changed chang

In [9]:
sen='i want to change world if world changed my carrer by changing life'
sen

'i want to change world if world changed my carrer by changing life'

In [11]:
from nltk.tokenize import word_tokenize
import nltk

In [13]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\dipto\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [14]:
token=word_tokenize(sen)
token

['i',
 'want',
 'to',
 'change',
 'world',
 'if',
 'world',
 'changed',
 'my',
 'carrer',
 'by',
 'changing',
 'life']

In [15]:
for w in token:
    print(w,p.stem(w))

i i
want want
to to
change chang
world world
if if
world world
changed chang
my my
carrer carrer
by by
changing chang
life life

Lemmatization

In [16]:
from nltk import WordNetLemmatizer

In [20]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dipto\AppData\Roaming\nltk_data...

True

In [21]:
le=WordNetLemmatizer()

In [22]:
token

['i',
 'want',
 'to',
 'change',
 'world',
 'if',
 'world',
 'changed',
 'my',
 'carrer',
 'by',
 'changing',
 'life']

In [23]:
for w in token:
    print(w,le.lemmatize(w))

i i
want want
to to
change change
world world
if if
world world
changed changed
my my
carrer carrer
by by
changing changing
life life

Text Vectorizer

In [27]:
import pandas as pd
import numpy as np
df=pd.read_csv('data.csv')

In [28]:
df

                           test  class
0             I love Bangladesh      1
1  Could you give me an iphone?      0
2            Hello how are you?      1
3           I want to talk you.      1

In [30]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

Count Vectorizer

In [36]:
cv=CountVectorizer()

In [37]:
cv_x=cv.fit_transform(df['test'])
cv_x

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 16 stored elements and shape (4, 14)>

In [38]:
cv_x.toarray()

array([[0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]])

In [41]:
cv.get_feature_names_out()

array(['an', 'are', 'bangladesh', 'could', 'give', 'hello', 'how',
       'iphone', 'love', 'me', 'talk', 'to', 'want', 'you'], dtype=object)

In [44]:
cv_df=pd.DataFrame(cv_x.toarray(),columns=cv.get_feature_names_out(),index=df['test'])
cv_df

,an,are,bangladesh,could,give,hello,how,iphone,love,me,talk,to,want,you
test,,,,,,,,,,,,,,
I love Bangladesh,0,0,1,0,0,0,0,0,1,0,0,0,0,0
Could you give me an iphone?,1,0,0,1,1,0,0,1,0,1,0,0,0,1
Hello how are you?,0,1,0,0,0,1,1,0,0,0,0,0,0,1
I want to talk you.,0,0,0,0,0,0,0,0,0,0,1,1,1,1

TfidfVectorizer(tf=term_frequency and idf=inverse_document_frequency)

In [62]:
tf=TfidfVectorizer()

In [48]:
tf_z=tf.fit_transform(df['test'])
tf_z

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16 stored elements and shape (4, 14)>

In [51]:
cv_z=pd.DataFrame(tf_z.toarray(),columns=tf.get_feature_names_out(),index=df['test'])
cv_z

,an,are,bangladesh,could,give,hello,how,iphone,love,me,talk,to,want,you
test,,,,,,,,,,,,,,
I love Bangladesh,0.000000,0.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000
Could you give me an iphone?,0.430037,0.000000,0.000000,0.430037,0.430037,0.000000,0.000000,0.430037,0.000000,0.430037,0.000000,0.000000,0.000000,0.274487
Hello how are you?,0.000000,0.541736,0.000000,0.000000,0.000000,0.541736,0.541736,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.345783
I want to talk you.,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.541736,0.541736,0.541736,0.345783

Word2Vec

In [53]:
!pip install gensim

Requirement already satisfied: gensim in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (from gensim) (2.3.5)
Requirement already satisfied: scipy>=1.7.0 in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in c:\users\dipto\appdata\local\programs\python\python313\lib\site-packages (from smart_open>=1.8.1->gensim) (2.0.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [55]:
from gensim.models import Word2Vec,KeyedVectors

In [56]:
text_vector=[nltk.word_tokenize(test) for test in df['test']]
text_vector

[['I', 'love', 'Bangladesh'],
 ['Could', 'you', 'give', 'me', 'an', 'iphone', '?'],
 ['Hello', 'how', 'are', 'you', '?'],
 ['I', 'want', 'to', 'talk', 'you', '.']]

In [58]:
model = Word2Vec(text_vector,min_count=1)

In [59]:
model.wv.most_similar('want')

[('love', 0.16378769278526306),
 ('I', 0.1459505707025528),
 ('iphone', 0.05048206448554993),
 ('.', 0.04157936945557594),
 ('talk', 0.03477078303694725),
 ('to', 0.019153937697410583),
 ('you', 0.01613837480545044),
 ('give', 0.012811623513698578),
 ('how', 0.008826171047985554),
 ('Could', 0.007729304954409599)]

In [60]:
model.wv.most_similar('give')

[('talk', 0.25288939476013184),
 ('?', 0.13725271821022034),
 ('to', 0.04410816729068756),
 ('Could', 0.02700837142765522),
 ('want', 0.01281161978840828),
 ('.', 0.006604064255952835),
 ('iphone', -0.0011978191323578358),
 ('are', -0.025461023673415184),
 ('love', -0.03247775509953499),
 ('you', -0.04124633967876434)]