In [1]:
import pandas as pd
import numpy as np
import seaborn as ans
from matplotlib import pyplot as plt

In [2]:
df=pd.read_csv('shoe.csv')
df.head()

   size(cm) class(y)
0     9.500   Female
1    10.125     Male
2    10.410     Male
3     9.810   Female
4    11.050     Male

In [3]:
df.isnull().sum()

size(cm)    0
class(y)    0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   size(cm)  40 non-null     float64
 1   class(y)  40 non-null     object
dtypes: float64(1), object(1)
memory usage: 772.0+ bytes

In [7]:
df['class(y)']=df['class(y)'].replace(['Female','Male'],[0,1])
df.head()

C:\Users\dipto\AppData\Local\Temp\ipykernel_14604\240935299.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['class(y)']=df['class(y)'].replace(['Female','Male'],[0,1])

   size(cm)  class(y)
0     9.500         0
1    10.125         1
2    10.410         1
3     9.810         0
4    11.050         1

In [29]:
x=df.drop('class(y)',axis=1)
x.head()
x.shape

(40, 1)

In [30]:
y=df[['class(y)']]
y.shape

(40, 1)

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
reg=LogisticRegression()

In [33]:
reg.fit(x,y)

C:\Users\dipto\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [46]:
reg.coef_

array([[2.62700105]])

In [47]:
reg.intercept_

array([-26.18202542])

In [48]:
reg.predict_proba(x)

array([[0.7730327 , 0.2269673 ],
       [0.39738803, 0.60261197],
       [0.23774988, 0.76225012],
       [0.60136241, 0.39863759],
       [0.05487101, 0.94512899],
       [0.89519741, 0.10480259],
       [0.79524978, 0.20475022],
       [0.17003549, 0.82996451],
       [0.66236362, 0.33763638],
       [0.69666466, 0.30333534],
       [0.59504837, 0.40495163],
       [0.23302194, 0.76697806],
       [0.357297  , 0.642703  ],
       [0.07737522, 0.92262478],
       [0.17757917, 0.82242083],
       [0.11860619, 0.88139381],
       [0.46492641, 0.53507359],
       [0.52395788, 0.47604212],
       [0.29398963, 0.70601037],
       [0.16274887, 0.83725113],
       [0.38177164, 0.61822836],
       [0.83473521, 0.16526479],
       [0.88221925, 0.11778075],
       [0.13921733, 0.86078267],
       [0.71305649, 0.28694351],
       [0.21477057, 0.78522943],
       [0.29947158, 0.70052842],
       [0.09833563, 0.90166437],
       [0.21923404, 0.78076596],
       [0.11860619, 0.88139381],
       [0.45188307, 0.54811693],
       [0.53704324, 0.46295676],
       [0.24254341, 0.75745659],
       [0.72890721, 0.27109279],
       [0.37559089, 0.62440911],
       [0.85206825, 0.14793175],
       [0.87946204, 0.12053796],
       [0.17377501, 0.82622499],
       [0.72368512, 0.27631488],
       [0.84532246, 0.15467754]])

In [49]:
reg.predict(x)

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0])